[Unit]
After=wireguard-ops-cockpit-agent.service wireguard-ops-cockpit-executor.service
Requires=wireguard-ops-cockpit-agent.service wireguard-ops-cockpit-executor.service

[Service]
SupplementaryGroups=cockpit-agent-client cockpit-executor-client
